documents:
  - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_head/*.gz

dedupe:
  name: dedupe_docs_v3
  paragraphs:
    attribute_name: bff_duplicate_docs
  skip_empty: false

bloom_filter:
  file: /tmp/cc_en_head.bloom
  read_only: false
  estimated_doc_count: 30000000000
  desired_false_positive_rate: 1e-06

processes: 188
