documents:
  - s3://ai2-llm/pretraining-data/sources/c4/v0/documents/train/*.gz

dedupe:
  name: perplexity_suite_v3_option2_redo
  paragraphs:
    attribute_name: bff_duplicate_paragraph_spans_decontamination
  skip_empty: true

bloom_filter:
  read_only: true
  estimated_doc_count: 488541
  size_in_bytes: 33554432  # 100 MB; smaller causes too many FPs
  file: s3://ai2-llm/bloom-filters/perplexity-suite-v3_option2.bin

processes: 224

work_dir:
  input: /mnt/tank/dolma_tmp/c4_input
  output: /mnt/tank/dolma_tmp/c4_output