documents:
  - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_head/*.gz
  - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_middle/*.gz
  - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_tail/*.gz
  # - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_head/cc_en_head-0000.json.gz

dedupe:
  name: perplexity_suite_v3_option1
  paragraphs:
    attribute_name: bff_duplicate_paragraph_spans_decontamination
  skip_empty: true

bloom_filter:
  read_only: true
  estimated_doc_count: 759208
  size_in_bytes: 104857600  # 100 MB; smaller causes too many FPs
  file: s3://ai2-llm/bloom-filters/perplexity-suite-v3_option1.bin

# bloom_filter:
#   read_only: true
#   estimated_doc_count: 187966
#   desired_false_positive_rate: 0.000001
#   file: s3://ai2-llm/bloom-filters/perplexity-suite-v2-8M.bin


# bloom_filter:
#   file": s3://ai2-llm/bloom-filters/deduper_decontamination_lucas_20230525.bin
#   size_in_bytes": 8388608
#   read_only": true
#   estimated_doc_count": 3898706
#   desired_false_positive_rate": 0.001


processes: 188
