streams:
- name: stack-v4-train
  documents:
  - pretraining-data/sources/stack-dedup/v2-train/documents/*.gz
  output:
    path: pretraining-data/sources/olmo-mix/v1_5/documents/stack
    max_size_in_bytes: 3894967296
    discard_fields:
    - attributes

  attributes:
    - perplexity_suite_v3_option2

  filter:
    include: []
    exclude:
    - "$@.attributes[?(@.bff_duplicate_paragraph_spans && @.bff_duplicate_paragraph_spans[0]
      && @.bff_duplicate_paragraph_spans[0][2] >= 1.0)]"


work_dir:
  input: "/tmp/olmo-mix-v1_5/input"
  output: "/tmp/olmo-mix-v1_5/output"
processes: 188
