streams:
  - name: dolma_eval

    documents:
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=0/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=1/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=2/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=3/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=4/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=5/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=6/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=7/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=8/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2orc/split=valid/part_id=9/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=0/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=1/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=2/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=3/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=4/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=5/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=6/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=7/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=8/*.gz
      - s3://ai2-llm/pretraining-data/sources/s2/v3/documents/dataset=s2ag/split=valid/part_id=9/*.gz

    output:
      path: s3://ai2-llm/pretraining-data/sources/olmo-mix/v1_5-eval/documents/pes2o

      #feed about ~50GB per process
      max_size_in_bytes: 50_000_000_000
      discard_fields:
        - attributes
        - metadata

    attributes:
      - random

    filter:
      include:
        # only keep 5% of the documents
        - $.attributes[?(@.random__random_number_v1__random[0][2] < 0.05)]

processes: 188
