documents:
  - ${oc.env:HOME}/perplexity/option1/documents/*.gz

dedupe:
  name: perplexity_suite_v3
  paragraphs:
    attribute_name: bff_duplicate_paragraph_spans
  skip_empty: true

bloom_filter:
  read_only: false
  estimated_doc_count: 759208
  desired_false_positive_rate: 0.00001
  file: s3://ai2-llm/bloom-filters/perplexity-suite-v3_option1.bin

processes: 188
