documents:
  - ${oc.env:HOME}/perplexity/option3/documents/*.gz

dedupe:
  name: perplexity_suite_v3
  paragraphs:
    attribute_name: bff_duplicate_paragraph_spans
  skip_empty: true

bloom_filter:
  read_only: false
  estimated_doc_count: 328571
  desired_false_positive_rate: 0.000001
  file: s3://ai2-llm/bloom-filters/perplexity-suite-v3_option3.bin

processes: 188
