documents:
  - s3://ai2-llm/pretraining-data/sources/common-crawl/v1-c4-cleaned/documents/cc_en_head/*.gz

dedupe:
  name: dedupe_docs
  documents:
    attribute_name: bff_duplicate_docs
    key: $.text
  skip_empty: true

bloom_filter:
  file: /tmp/cc_en_head/bloom.bin
  read_only: false
  estimated_doc_count: 30000000000
  desired_false_positive_rate: 1e-06

work_dir:
  input: /tmp/cc_en_head/input
  output: /tmp/cc_en_head/output

processes: 188
